### ISSUE TITLE
Could a browser bundle be published alongside the module?

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril-query#102]
It's currently a bit awkward to use in a browser without a bundler already set up, so I was wondering if you could start publishing a browser bundle distribution that I could point users to.

For context, I *was* going to include a "Running in browsers" section for the rewritten testing docs (soon to be published), but I don't want to include it with nothing to point to, and I want it to be easy to get started with.

**Comment by StephanHoyer** [comment]
I think there are already solutions for testing an app in the browser. But I'm not experienced with that. Maybe something like jest?

**Comment by isiahmeadows** [comment]
Mocha supports both using Karma/etc. and just loading it via `<script src="path/to/mocha.js"></script>` + `<link rel="stylesheet" src="path/to/mocha.css">`. Chai also supports similar usage. Sometimes, the easiest way to set everything up is the way it was done in the dark ages. 😉😄

**Comment by StephanHoyer** [comment]
close this for now, since you seem to have found a solution
