### ISSUE TITLE
Can't access DOM of child VNodes

### ISSUE THREAD

**Issue by Manidos** [MithrilJS/mithril-query#103]
Hey! Here's my simple testing setup. It gives me an error `TypeError: Cannot set property 'value' of undefined at Object.setValue`. What am I missing?

```
const mq = require('mithril-query')
const m = require('mithril')

const Component = {
    view () {
      this.input = m('input')
      return m('div', this.input)
    },
    setValue (value) {
      this.input.dom.value = value
    }
}

describe('Component', function() {
  const out = mq(Component)
  it('displays correct value after `setValue` call', function() {
    out.vnode.state.setValue('test')
  });
});
```

**Comment by StephanHoyer** [comment]
Since this is running in Node, DOM access is currently not supported. I think about using a dom mock, but this makes testing a lot slower. Maybe we could create a "Dom-Mode" as opt in.
