### ISSUE TITLE
support closure components

### ISSUE THREAD

**Issue by mzknksh** [MithrilJS/mithril-query#77]
Just started learning Mithril 1.1.1 few days ago and went with https://mithril.js.org/components.html#closure-components - those are however not supported by mq.

**Comment by StephanHoyer** [comment]
Currently have no time to implement this. But I think it would be pretty easy to do.

see https://github.com/StephanHoyer/mithril-node-render/commit/00caf16ac02c41ea1b191162280fc858d5d244f6

Modules are pretty similar.

Maybe you can create a PR?
