### ISSUE TITLE
Rewrite this on top of `m.render` + cssauron-html?

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril-query#79]
Hi @StephanHoyer I've been reviewing the source in order to implement class components, and the way `m.render`/`m.redraw` are implemented is not very accurate.

Rather than rewriting the whole thing, I was wondering if we couldn't instead rely on `m.render()`, some kind of DOM library (injectable, so that `jsdom` can be used optionally if the Mithril mocks don't cut it for someone) and [cssauron-html](https://github.com/chrisdickinson/cssauron-html)?

After `renderComponents()` is removed, It looks like there's little code that's vdom specific beside the `language()` parser and the `select()` function.

That approach would ensure feature parity with Mithril, and allow to support more complex components that manipulate their DOM in hooks.

Edit: Looking a bit deeper into this, the `removers` feature couldn't be replicated, but we could instead add a `api.remove()` method that would `m.render(root, [])`, thereby triggering the removal phase.

Edit2: the event handling code would also need some love. Another breaking change would be the fact that `api.rootNode` would be a DOM tree rather than a vDOM tree. Some workaround would be needed if the root component returns an array.

**Comment by pygy** [comment]
It would definitely be slower than what you have now, but it would also be more correct, for a variety of scenarios (support all hooks, keyed diff, proper state). The Mithril mocks are probably sufficient for this, and faster than jsdom. I'll give it a try.

The mocks have been re-written for Mithril v1, hopefully they are better suited than the previous version. A possible problem is that they don't implement every element property getter/setter that real DOM nodes do, which means that some values would end up being set as attributes instead of properties...

The result would not be 100% compatible though, because some functions that currently return elements would return DOM nodes instead.

I already worked on this a bit, but m gf drove on my laptop in the mean time (my fault :-/, I had left it leaning on the bumper), and I have to recover the files from the HD (which is intact).

**Comment by StephanHoyer** [comment]
I just tried to implement class components. It's tricky and you are right for sure. 100% compatibility with core would be pretty cool.

**Comment by StephanHoyer** [comment]
obsolete now as we use domino
