### ISSUE TITLE
should.have('... :contains') not always working

### ISSUE THREAD

**Issue by der-On** [MithrilJS/mithril-query#81]
In some cases the `:contains` directive is not working as expected.

Example:

```javascript
const out = mq(myComponent);
out.should.have('.button :contains(foo)'); // will return 0 elements, also the button is there
```

```javascript
const out = mq(myComponent);
mq(out.first('.button')).should.contain('foo'); // will work however
```

In other case the `:contains` directive is working as expected.

**Comment by StephanHoyer** [comment]
Can you provide a tests case for this?

**Comment by der-On** [comment]
I've now created a failing test in #82

**Comment by StephanHoyer** [comment]
Oh, now I see. `should`-style assertions never return anything but throw in case they are not fulfilled. Maybe I should change that.

**Comment by StephanHoyer** [comment]
also your selector is wrong I think, should be `.button:contains(foo)`

**Comment by der-On** [comment]
@StephanHoyer thank you. I guess your readme about the :contains selector could be updated to contain a class-name before the `:contains(...)`

**Comment by StephanHoyer** [comment]
@der-On It's standard css syntax I guess. But I will do this.
