### ISSUE TITLE
Missing test for traversing children for sibling

### ISSUE THREAD

**Issue by SamuelTilly** [MithrilJS/mithril-query#90]
While i was logging inside the `children` function for the cssauroun implementation there looks to be nothing that tests that the sibling function behaves as expected.

Adjacent sibling: https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors
General sibling: https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_selectors

```javascript
describe('traverse from a parent to its children for sibling selectors', function() {
  it('adjacent sibling combinator ', function() {
    let output = mq(m('div', [
      m('div.first'),
      m('div.second')
    ]))

    output.should.have('.first + .second')
  })

  it('general sibling combinator', function() {
    let output = mq(m('div', [
      m('span'),
      m('p'),
      m('span'),
      m('a'),
      m('span')
    ]))

    expect(output.find('p ~ span').length).toEqual(2)
  })
})
```
This simple tests validate that the implementation indeed works as intended :+1:

**Comment by StephanHoyer** [comment]
add this to the tests, thanks.
