### ISSUE TITLE
Tests are failing in IE because of non passive change in 2.5.0 version

### ISSUE THREAD

**Issue by agrandhi18** [MithrilJS/mithril-query#94]
Because of declaring variables as const [here](https://github.com/MithrilJS/mithril-query/blob/c93fb7c293822d450576067f7b60559cc7750210/index.js#L3-L5), tests are failing when they are ran in IE or phantom.js. We would need to transpile or revert them back to var.

**Comment by StephanHoyer** [comment]
mithril-query is targeting node as runtime. If you run in real browsers, you can use something like jquery to test your stuff.

**Comment by SamuelTilly** [comment]
As previously mentioned mithril-query is only useful in a headless environment and no counter argument have been made :) voting for a close on this issue
