### ISSUE TITLE
Closure components clarification

### ISSUE THREAD

**Issue by gilbert** [MithrilJS/mithril-query#99]
The readme states "Closure Components are currently only supported as part of the tree, not directly as argumend to mq function". Can you give an example of what is and isn't acceptable?

**Comment by StephanHoyer** [comment]
it's outdated, Closure components are fully supported since https://github.com/MithrilJS/mithril-query/commit/919da9792c8f9cf7dc86bfaabca24c314d184f67

**Comment by StephanHoyer** [comment]
[cleaned](https://github.com/MithrilJS/mithril-query/commit/61a3406bfcf51eee15c4ae73c142c2c394efe4ee
) up the part of the docs.

Thanks for pointing this out
